package main

import (
	"encoding/binary"
	"net"
	"testing"
)

func TestDHCPHandWrittenCodecAndRequiredOptions(t *testing.T) {
	mac := net.HardwareAddr{0, 1, 2, 3, 4, 5}
	// These option tails are deliberately hand-written wire bytes rather than
	// generated by the encoder: the codec test must exercise interop decoding.
	discoverHeader := make([]byte, 240)
	discoverHeader[0], discoverHeader[1], discoverHeader[2] = 1, 1, 6
	binary.BigEndian.PutUint32(discoverHeader[4:8], 0x11223344)
	binary.BigEndian.PutUint32(discoverHeader[236:240], dhcpCookie)
	discoverRaw := append(discoverHeader, []byte{53, 1, 1, 55, 7, 1, 3, 6, 51, 54, 66, 150, 255}...)
	if raw, err := DecodeDHCP(discoverRaw); err != nil || raw.Options[53][0] != 1 {
		t.Fatalf("hand-written discover: %v %#v", err, raw)
	}
	offerHeader := append([]byte(nil), discoverHeader...)
	offerHeader[16], offerHeader[17], offerHeader[18], offerHeader[19] = 192, 0, 2, 44
	offerRaw := append(offerHeader, []byte{
		1, 4, 255, 255, 255, 0,
		3, 4, 192, 0, 2, 1,
		6, 8, 192, 0, 2, 53, 1, 1, 1, 1,
		51, 4, 0, 0, 14, 16,
		54, 4, 192, 0, 2, 1,
		66, 5, 't', 'f', 't', 'p', 0,
		150, 4, 192, 0, 2, 2,
		255,
	}...)
	offerWire, err := DecodeDHCP(offerRaw)
	if err != nil {
		t.Fatal(err)
	}
	lease := leaseFromOffer(offerWire)
	if lease.Router != "192.0.2.1" || len(lease.DNS) != 2 || lease.LeaseSeconds == 0 || lease.ServerID != "192.0.2.1" || lease.TFTPName != "tftp" || len(lease.TFTPServers) != 1 {
		t.Fatalf("decoded offer lease = %#v", lease)
	}

	discover := BuildDHCPDiscover(0x11223344, mac)
	wire := discover.Encode()
	decoded, err := DecodeDHCP(wire)
	if err != nil {
		t.Fatal(err)
	}
	if decoded.XID != 0x11223344 || decoded.Options[53][0] != 1 {
		t.Fatalf("discover = %#v", decoded)
	}
	for _, code := range []byte{1, 3, 6, 51, 54, 66, 150} {
		decoded.Options[code] = []byte{1, 2, 3, 4}
	}
	decoded.Options[53] = []byte{2}
	decoded.YourIP = net.ParseIP("192.0.2.44")
	decoded.ServerIP = net.ParseIP("192.0.2.1")
	offer, err := DecodeDHCP(decoded.Encode())
	if err != nil {
		t.Fatal(err)
	}
	for _, code := range []byte{1, 3, 6, 51, 54, 66, 150} {
		if len(offer.Options[code]) == 0 {
			t.Fatalf("offer omitted option %d", code)
		}
	}
	request := BuildDHCPRequest(offer.XID, mac, offer.YourIP, offer.ServerIP)
	if request.Options[53][0] != 3 || string(request.Options[50]) != string(offer.YourIP.To4()) {
		t.Fatalf("request = %#v", request.Options)
	}
	lease = leaseFromOffer(offer)
	if lease.ServerID == "" {
		t.Fatal("lease server id missing")
	}
	_ = binary.BigEndian
}
